spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_empreitadas
spring.datasource.username=postgres
spring.datasource.password=DiogoCosta2012&
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Porta do servidor web
server.port=8080

# Modo: false = servidor web ligado | true = correr testes BLL
app.run-tests=false

# Desativar banner desnecessário
spring.main.banner-mode=console