spring.datasource.url=jdbc:postgresql://localhost:5432/gestao_empreitadas
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:DiogoCosta2012&}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Recursos estaticos servidos a partir de /web/
spring.web.resources.static-locations=classpath:/static/web/
spring.mvc.static-path-pattern=/**

server.port=8080

# false = servidor web | true = testes BLL
app.run-tests=false

spring.main.banner-mode=off